import { serializePropValue } from '@json-render/codegen';
import type { PreparedExport, PreparedSpecData } from '../types';

/**
 * Generate a TypeScript data file from PreparedSpecData.
 * Only includes exports referenced in the spec (by usedExportIds).
 * Strips rawExport to reduce size.
 */
export function generateDataFile(
  data: PreparedSpecData,
  usedExportIds: string[],
): string {
  const trimmed = trimData(data, usedExportIds);
  const serialized = serializeData(trimmed);

  return [
    `// Generated by @openpkg-ts/json-render codegen`,
    `// Do not edit manually`,
    ``,
    `export const specData = ${serialized} as const;`,
    ``,
    `export type SpecData = typeof specData;`,
    ``,
  ].join('\n');
}

/** Strip rawExport and filter to only used exports */
function trimData(
  data: PreparedSpecData,
  usedExportIds: string[],
): Omit<PreparedSpecData, 'exportsByKind'> & { exports: Record<string, Omit<PreparedExport, 'rawExport'>> } {
  const exports: Record<string, Omit<PreparedExport, 'rawExport'>> = {};

  for (const id of usedExportIds) {
    const exp = data.exports[id];
    if (!exp) continue;
    const { rawExport: _, ...rest } = exp;
    exports[id] = rest;
  }

  return {
    packageName: data.packageName,
    packageDescription: data.packageDescription,
    exports,
    allExportIds: usedExportIds.filter((id) => data.exports[id]),
  };
}

/** Deep serialize to valid TS source */
function serializeData(obj: unknown): string {
  return serializeValue(obj, 0);
}

function serializeValue(value: unknown, depth: number): string {
  const indent = '  '.repeat(depth);
  const indent2 = '  '.repeat(depth + 1);

  if (value === null || value === undefined) {
    return String(value);
  }

  if (typeof value === 'string') {
    return serializePropValue(value).value;
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => `${indent2}${serializeValue(v, depth + 1)}`);
    return `[\n${items.join(',\n')}\n${indent}]`;
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return '{}';

    const props = entries.map(([key, val]) => {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
      return `${indent2}${safeKey}: ${serializeValue(val, depth + 1)}`;
    });

    return `{\n${props.join(',\n')}\n${indent}}`;
  }

  return String(value);
}
