// Re-export Fumadocs source integration

// Re-export spec types for convenience
export type {
  DocsInstance as OpenPkgInstance,
  LoadOptions as OpenPkgOptions,
  OpenPkg,
  SpecExample,
  SpecExport,
  SpecExportKind,
  SpecMember,
  SpecSchema,
  SpecSignature,
  SpecSignatureParameter,
  SpecTag,
  SpecType,
  SpecTypeKind,
  SpecTypeParameter,
} from '@openpkg-ts/doc-generator';
export {
  type AlgoliaRecord,
  buildSignatureString,
  createDocs,
  createDocs as createOpenPkg,
  type DocsInstance,
  type ExportMarkdownOptions,
  exportToMarkdown,
  formatParameters,
  formatReturnType,
  formatSchema,
  formatTypeParameters,
  getMethods,
  getProperties,
  groupByVisibility,
  type HTMLOptions,
  isMethod,
  isProperty,
  type JSONOptions,
  type LoadOptions,
  loadSpec,
  type MarkdownOptions,
  type NavOptions,
  type PagefindRecord,
  resolveTypeRef,
  type SearchIndex,
  type SearchOptions,
  type SearchRecord,
  sortByName,
  toAlgoliaRecords,
  toDocusaurusSidebarJS,
  toFumadocsMetaJSON,
  toHTML,
  toJSON,
  toJSONString,
  toMarkdown,
  toNavigation,
  toPagefindRecords,
  toSearchIndex,
  toSearchIndexJSON,
} from '@openpkg-ts/doc-generator';
// Re-export styled components (most common use case)
export {
  APIPage,
  type APIPageProps,
  ClassPage,
  type ClassPageProps,
  ClassSection,
  type ClassSectionProps,
  type CodeTab,
  CodeTabs,
  type CodeTabsProps,
  EnumPage,
  type EnumPageProps,
  EnumSection,
  type EnumSectionProps,
  ExportCard,
  type ExportCardProps,
  ExportIndexPage,
  type ExportIndexPageProps,
  ExportSection,
  type ExportSectionProps,
  FullAPIReferencePage,
  type FullAPIReferencePageProps,
  FunctionPage,
  type FunctionPageProps,
  FunctionSection,
  type FunctionSectionProps,
  ImportSection,
  type ImportSectionProps,
  InterfacePage,
  type InterfacePageProps,
  InterfaceSection,
  type InterfaceSectionProps,
  type NestedPropertyItemProps,
  ParameterItem,
  type ParameterItemProps,
  VariablePage,
  type VariablePageProps,
  VariableSection,
  type VariableSectionProps,
} from '@openpkg-ts/doc-generator/react/styled';
// Re-export sidebar badge component (alias for KindBadge)
export {
  SidebarKindBadge,
  type SidebarKindBadgeProps,
} from './components/sidebar-badge';
// Re-export Fumadocs plugin integration
export {
  KindBadge,
  type KindBadgeProps,
  type OpenpkgPluginOptions,
  openpkgPlugin,
} from './plugin';
export {
  type OpenPkgIndexPageData,
  type OpenPkgMetaData,
  type OpenPkgPageData,
  type OpenPkgSinglePageData,
  type OpenPkgSourceOptions,
  openpkgSource,
} from './source';
