// React components — styled with Tailwind v4
// Note: index.ts re-exports styled.js at the dist level.
// Both entry points compile to the same code; index.js just proxies styled.js.
export {
  // Adapters
  buildImportStatement,
  generateDefaultExample,
  getLanguagesFromExamples,
  resolveSchemaRef,
  specExampleToCodeExample,
  specExamplesToCodeExamples,
  specParamToAPIParam,
  specParamToNestedParam,
  specParamsToNestedParams,
  specSchemaToAPISchema,
  // Hooks
  extractMethodData,
  useMethodFromSpec,
  useMethodsFromSpec,
  // UI re-exports
  CodeTabs,
  ImportSection,
  // Components
  APIPage,
  APIParameterItem,
  APIReferenceLayout,
  ClassPage,
  ClassSection,
  CodeBlock,
  CollapsiblePanel,
  EnumPage,
  EnumSection,
  EnumValuesSection,
  ExampleChips,
  ExampleSection,
  ExpandableParameter,
  ExportCard,
  ExportIndexPage,
  ExportSection,
  FullAPIReferencePage,
  FunctionPage,
  FunctionSection,
  InterfacePage,
  InterfaceSection,
  MethodSection,
  MethodSectionFromSpec,
  NestedParameterContainer,
  NestedParameterToggle,
  StripeAPIReferencePage,
  SyncScrollProvider,
  useSyncScroll,
  useSyncSection,
  VariablePage,
  VariableSection,
} from './styled';
// Type re-exports
export type {
  APIPageProps,
  APIParameterItemProps,
  APIReferenceLayoutProps,
  ClassPageProps,
  ClassSectionProps,
  CodeBlockProps,
  CodeExample,
  CodePanelProps,
  CodeTab,
  CodeTabsProps,
  CollapsiblePanelProps,
  EnumPageProps,
  EnumSectionProps,
  EnumValue,
  EnumValuesSectionProps,
  ExampleChip,
  ExampleChipsProps,
  ExampleSectionProps,
  ExpandableParameterProps,
  ExportCardProps,
  ExportIndexPageProps,
  ExportSectionProps,
  FullAPIReferencePageProps,
  FunctionPageProps,
  FunctionSectionProps,
  ImportSectionProps,
  InterfacePageProps,
  InterfaceSectionProps,
  MethodData,
  MethodSectionFromSpecProps,
  MethodSectionProps,
  NestedParameterContainerProps,
  NestedParameterData,
  NestedParameterToggleProps,
  StripeAPIReferencePageProps,
  SyncScrollContextValue,
  SyncScrollProviderProps,
  VariablePageProps,
  VariableSectionProps,
} from './styled';
